// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCustomPromptReducer from "../add_custom_prompt_reducer";
import ClearRoastReactionReducer from "../clear_roast_reaction_reducer";
import ConsumeSignalReducer from "../consume_signal_reducer";
import CreateRoomReducer from "../create_room_reducer";
import DeleteMessageReducer from "../delete_message_reducer";
import DeleteMomentReducer from "../delete_moment_reducer";
import DeleteRoastReducer from "../delete_roast_reducer";
import DeleteRoomReducer from "../delete_room_reducer";
import DismissRoomPromptReducer from "../dismiss_room_prompt_reducer";
import JoinRoomReducer from "../join_room_reducer";
import JoinVoiceReducer from "../join_voice_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import LeaveVoiceReducer from "../leave_voice_reducer";
import MarkRoomCaughtUpReducer from "../mark_room_caught_up_reducer";
import PingSpeakingReducer from "../ping_speaking_reducer";
import PostMomentReducer from "../post_moment_reducer";
import PostRoastReducer from "../post_roast_reducer";
import RemoveMemberReducer from "../remove_member_reducer";
import SaveProfileReducer from "../save_profile_reducer";
import SeedDemoRoomsReducer from "../seed_demo_rooms_reducer";
import SendMessageReducer from "../send_message_reducer";
import SendRoastReactionReducer from "../send_roast_reaction_reducer";
import SendSignalReducer from "../send_signal_reducer";
import SetActivityReducer from "../set_activity_reducer";
import SetMutedReducer from "../set_muted_reducer";
import SetRoastModeReducer from "../set_roast_mode_reducer";
import SetRoomPromptScheduleReducer from "../set_room_prompt_schedule_reducer";
import SetTypingReducer from "../set_typing_reducer";
import SetViewingReducer from "../set_viewing_reducer";
import StartVoiceReducer from "../start_voice_reducer";
import ToggleReactionReducer from "../toggle_reaction_reducer";
import TriggerPromptCycleReducer from "../trigger_prompt_cycle_reducer";
import UnvoteRoastReducer from "../unvote_roast_reducer";
import UpdateRoomReducer from "../update_room_reducer";
import VoteRoastReducer from "../vote_roast_reducer";

export type AddCustomPromptParams = __Infer<typeof AddCustomPromptReducer>;
export type ClearRoastReactionParams = __Infer<typeof ClearRoastReactionReducer>;
export type ConsumeSignalParams = __Infer<typeof ConsumeSignalReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DeleteMessageParams = __Infer<typeof DeleteMessageReducer>;
export type DeleteMomentParams = __Infer<typeof DeleteMomentReducer>;
export type DeleteRoastParams = __Infer<typeof DeleteRoastReducer>;
export type DeleteRoomParams = __Infer<typeof DeleteRoomReducer>;
export type DismissRoomPromptParams = __Infer<typeof DismissRoomPromptReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type JoinVoiceParams = __Infer<typeof JoinVoiceReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type LeaveVoiceParams = __Infer<typeof LeaveVoiceReducer>;
export type MarkRoomCaughtUpParams = __Infer<typeof MarkRoomCaughtUpReducer>;
export type PingSpeakingParams = __Infer<typeof PingSpeakingReducer>;
export type PostMomentParams = __Infer<typeof PostMomentReducer>;
export type PostRoastParams = __Infer<typeof PostRoastReducer>;
export type RemoveMemberParams = __Infer<typeof RemoveMemberReducer>;
export type SaveProfileParams = __Infer<typeof SaveProfileReducer>;
export type SeedDemoRoomsParams = __Infer<typeof SeedDemoRoomsReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SendRoastReactionParams = __Infer<typeof SendRoastReactionReducer>;
export type SendSignalParams = __Infer<typeof SendSignalReducer>;
export type SetActivityParams = __Infer<typeof SetActivityReducer>;
export type SetMutedParams = __Infer<typeof SetMutedReducer>;
export type SetRoastModeParams = __Infer<typeof SetRoastModeReducer>;
export type SetRoomPromptScheduleParams = __Infer<typeof SetRoomPromptScheduleReducer>;
export type SetTypingParams = __Infer<typeof SetTypingReducer>;
export type SetViewingParams = __Infer<typeof SetViewingReducer>;
export type StartVoiceParams = __Infer<typeof StartVoiceReducer>;
export type ToggleReactionParams = __Infer<typeof ToggleReactionReducer>;
export type TriggerPromptCycleParams = __Infer<typeof TriggerPromptCycleReducer>;
export type UnvoteRoastParams = __Infer<typeof UnvoteRoastReducer>;
export type UpdateRoomParams = __Infer<typeof UpdateRoomReducer>;
export type VoteRoastParams = __Infer<typeof VoteRoastReducer>;

