// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  memberId: __t.u64().name("member_id"),
  kind: __t.string(),
  url: __t.string(),
  mimeType: __t.string().name("mime_type"),
  width: __t.u32(),
  height: __t.u32(),
  durationMs: __t.u32().name("duration_ms"),
  sizeBytes: __t.u32().name("size_bytes"),
  waveform: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  posterUrl: __t.string().name("poster_url"),
});
