// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  momentId: __t.u64().name("moment_id"),
  membershipId: __t.u64().name("membership_id"),
  lineId: __t.u64().name("line_id"),
  customText: __t.string().name("custom_text"),
  heatLevel: __t.string().name("heat_level"),
  style: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
