// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  name: __t.string(),
  emoji: __t.string(),
  kind: __t.string(),
  coverUrl: __t.string().name("cover_url"),
  isEvent: __t.bool().name("is_event"),
  ownerId: __t.u64().name("owner_id"),
  createdAt: __t.timestamp().name("created_at"),
  lastActivityAt: __t.timestamp().name("last_activity_at"),
  roastMode: __t.bool().name("roast_mode"),
});
