// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  personId: __t.u64().name("person_id"),
  displayName: __t.string().name("display_name"),
  avatarUrl: __t.string().name("avatar_url"),
  status: __t.string(),
  activity: __t.string(),
  activityEmoji: __t.string().name("activity_emoji"),
  isDemo: __t.bool().name("is_demo"),
  viewing: __t.bool(),
  typingUntil: __t.timestamp().name("typing_until"),
  joinedAt: __t.timestamp().name("joined_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
  currentStreak: __t.u32().name("current_streak"),
  longestStreak: __t.u32().name("longest_streak"),
  lastMomentDate: __t.u32().name("last_moment_date"),
  lastReplayMicros: __t.u64().name("last_replay_micros"),
});
