// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roomId: __t.u64(),
  kind: __t.string(),
  text: __t.string(),
  momentId: __t.u64(),
  mediaUrl: __t.string(),
  posterUrl: __t.string(),
  mimeType: __t.string(),
  width: __t.u32(),
  height: __t.u32(),
  durationMs: __t.u32(),
  sizeBytes: __t.u32(),
  waveform: __t.string(),
};
