// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Badge = __t.object("Badge", {
  id: __t.u64(),
  membershipId: __t.u64(),
  badgeType: __t.string(),
  awardedAt: __t.timestamp(),
});
export type Badge = __Infer<typeof Badge>;

export const CustomPrompt = __t.object("CustomPrompt", {
  id: __t.u64(),
  roomId: __t.u64(),
  text: __t.string(),
  createdBy: __t.u64(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
});
export type CustomPrompt = __Infer<typeof CustomPrompt>;

export const DemoTickTimer = __t.object("DemoTickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DemoTickTimer = __Infer<typeof DemoTickTimer>;

export const Media = __t.object("Media", {
  id: __t.u64(),
  roomId: __t.u64(),
  memberId: __t.u64(),
  kind: __t.string(),
  url: __t.string(),
  posterUrl: __t.string(),
  mimeType: __t.string(),
  width: __t.u32(),
  height: __t.u32(),
  durationMs: __t.u32(),
  sizeBytes: __t.u32(),
  waveform: __t.string(),
  createdAt: __t.timestamp(),
});
export type Media = __Infer<typeof Media>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  roomId: __t.u64(),
  memberId: __t.u64(),
  kind: __t.string(),
  text: __t.string(),
  mediaId: __t.u64(),
  momentId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const Moment = __t.object("Moment", {
  id: __t.u64(),
  roomId: __t.u64(),
  memberId: __t.u64(),
  kind: __t.string(),
  mediaId: __t.u64(),
  caption: __t.string(),
  createdAt: __t.timestamp(),
});
export type Moment = __Infer<typeof Moment>;

export const Person = __t.object("Person", {
  id: __t.u64(),
  identity: __t.identity(),
  handle: __t.string(),
  displayName: __t.string(),
  avatarUrl: __t.string(),
  bio: __t.string(),
  createdAt: __t.timestamp(),
});
export type Person = __Infer<typeof Person>;

export const PromptLibrary = __t.object("PromptLibrary", {
  id: __t.u64(),
  roomType: __t.string(),
  text: __t.string(),
});
export type PromptLibrary = __Infer<typeof PromptLibrary>;

export const Reaction = __t.object("Reaction", {
  id: __t.u64(),
  momentId: __t.u64(),
  memberId: __t.u64(),
  emoji: __t.string(),
  createdAt: __t.timestamp(),
});
export type Reaction = __Infer<typeof Reaction>;

export const Roast = __t.object("Roast", {
  id: __t.u64(),
  roomId: __t.u64(),
  momentId: __t.u64(),
  authorMembershipId: __t.u64(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type Roast = __Infer<typeof Roast>;

export const RoastLineLibrary = __t.object("RoastLineLibrary", {
  id: __t.u64(),
  category: __t.string(),
  heatLevel: __t.string(),
  style: __t.string(),
  text: __t.string(),
});
export type RoastLineLibrary = __Infer<typeof RoastLineLibrary>;

export const RoastReaction = __t.object("RoastReaction", {
  id: __t.u64(),
  momentId: __t.u64(),
  membershipId: __t.u64(),
  lineId: __t.u64(),
  customText: __t.string(),
  heatLevel: __t.string(),
  style: __t.string(),
  createdAt: __t.timestamp(),
});
export type RoastReaction = __Infer<typeof RoastReaction>;

export const RoastVote = __t.object("RoastVote", {
  id: __t.u64(),
  roastId: __t.u64(),
  membershipId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type RoastVote = __Infer<typeof RoastVote>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  name: __t.string(),
  emoji: __t.string(),
  kind: __t.string(),
  coverUrl: __t.string(),
  isEvent: __t.bool(),
  ownerId: __t.u64(),
  createdAt: __t.timestamp(),
  lastActivityAt: __t.timestamp(),
  roastMode: __t.bool(),
});
export type Room = __Infer<typeof Room>;

export const RoomEvent = __t.object("RoomEvent", {
  id: __t.u64(),
  roomId: __t.u64(),
  kind: __t.string(),
  memberId: __t.u64(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type RoomEvent = __Infer<typeof RoomEvent>;

export const RoomMember = __t.object("RoomMember", {
  id: __t.u64(),
  roomId: __t.u64(),
  personId: __t.u64(),
  displayName: __t.string(),
  avatarUrl: __t.string(),
  status: __t.string(),
  activity: __t.string(),
  activityEmoji: __t.string(),
  isDemo: __t.bool(),
  viewing: __t.bool(),
  typingUntil: __t.timestamp(),
  joinedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  currentStreak: __t.u32(),
  longestStreak: __t.u32(),
  lastMomentDate: __t.u32(),
  lastReplayMicros: __t.u64(),
});
export type RoomMember = __Infer<typeof RoomMember>;

export const RoomPrompt = __t.object("RoomPrompt", {
  id: __t.u64(),
  roomId: __t.u64(),
  text: __t.string(),
  source: __t.string(),
  startedAt: __t.timestamp(),
});
export type RoomPrompt = __Infer<typeof RoomPrompt>;

export const RoomPromptSchedule = __t.object("RoomPromptSchedule", {
  id: __t.u64(),
  roomId: __t.u64(),
  scheduledTime: __t.string(),
  isActive: __t.bool(),
  source: __t.string(),
  lastFiredDate: __t.u32(),
});
export type RoomPromptSchedule = __Infer<typeof RoomPromptSchedule>;

export const RoomTitle = __t.object("RoomTitle", {
  id: __t.u64(),
  roomId: __t.u64(),
  memberId: __t.u64(),
  titleType: __t.string(),
  awardedForDate: __t.u32(),
});
export type RoomTitle = __Infer<typeof RoomTitle>;

export const Signal = __t.object("Signal", {
  id: __t.u64(),
  sessionId: __t.u64(),
  fromMemberId: __t.u64(),
  toMemberId: __t.u64(),
  kind: __t.string(),
  payload: __t.string(),
  createdAt: __t.timestamp(),
});
export type Signal = __Infer<typeof Signal>;

export const SweepTimer = __t.object("SweepTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type SweepTimer = __Infer<typeof SweepTimer>;

export const VoiceParticipant = __t.object("VoiceParticipant", {
  id: __t.u64(),
  sessionId: __t.u64(),
  roomId: __t.u64(),
  memberId: __t.u64(),
  personId: __t.u64(),
  muted: __t.bool(),
  speakingUntil: __t.timestamp(),
  joinedAt: __t.timestamp(),
});
export type VoiceParticipant = __Infer<typeof VoiceParticipant>;

export const VoiceSession = __t.object("VoiceSession", {
  id: __t.u64(),
  roomId: __t.u64(),
  startedBy: __t.u64(),
  startedAt: __t.timestamp(),
});
export type VoiceSession = __Infer<typeof VoiceSession>;

